# Generated by Django 3.2.9 on 2021-11-14 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 11, 14, 16, 32, 20, 925179, tzinfo=utc), null=True),
        ),
    ]
