# Generated by Django 3.2.9 on 2021-11-17 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20211115_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_owner_reverse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchclass',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_owner_reverse', to=settings.AUTH_USER_MODEL),
        ),
    ]
