# Generated by Django 3.2.9 on 2021-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211118_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclass',
            name='class_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
