# Generated by Django 3.2.9 on 2021-11-18 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_batchclass_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclass',
            name='third_party_user',
            field=models.ManyToManyField(related_name='third_party_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
