# Generated by Django 3.2.9 on 2021-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_batchclass_third_party_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclass',
            name='student_class_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
