# Generated by Django 3.2.9 on 2021-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_batchclass_third_party_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
