# Generated by Django 3.2.9 on 2021-11-25 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studentsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 25, 18, 42, 22, 645067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
