# Generated by Django 3.2.9 on 2021-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentsubmission_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='remark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
