# Generated by Django 3.2.9 on 2021-11-27 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studentsubmission_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
