# Generated by Django 3.2.9 on 2021-11-27 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_extendeduser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
